---
- hosts: localhost
  connection: local
  gather_facts: no
  sudo: no
  tasks:
    - name: Create sacloud resources
      sacloud:
        access_token: "{{ lookup('env', 'ACCESS_TOKEN')  }}"
        access_token_secret: "{{ lookup('env', 'ACCESS_TOKEN_SECRET')  }}"
        zone_id: is1a
        archive_resource_id: "{{ lookup('env', 'ARCHIVE_RESOURCE_ID') }}"
        disk_icon: Ubuntu
        disk_plan: ssd
        disk_size: 20
        disk_desc: |-
          this
          is
          a
          disk
        disk_name: test disk
        disk_tags:
          - virtio-net-pci
          - boot-cdrom
        disk_config_host_name: example.com
        disk_config_password: pAssw0rd
        disk_config_ssh_key: "{{ lookup('file', 'id_rsa.pub') }}"
        server_cpu: 1
        server_mem: 1
        server_icon: Ubuntu
        server_desc: |-
          this
          is
          a
          server
        server_name: test server
        server_tags:
          - group=a
          - keyboard-us
        state: present
      tags:
        - bootstrap
